In [ ]:
# 1. Import the numpy package under the name np and Print the numpy version and the configuration

import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
# 2. Create a null vector of size 10

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# 3. Create Simple 1-D array and check type and check data types in array

arr = np.array(10)
print(type(arr))
print(arr.dtype)

<class 'numpy.ndarray'>
int64


In [ ]:
# 4. How to find number of dimensions, bytes per element and bytes of memory used 

arr = np.arange(5)
print("Dimension = ", arr.ndim)
print("Bytes Per Element = ",arr.itemsize)
print("Bytes of memory used = ", arr.size * arr.itemsize)

Dimension =  1
Bytes Per Element =  8
Bytes of memory used =  40


In [ ]:
# 5. Create a null vector of size 10 but the fifth value which is 1

arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
# 6. Create a vector with values ranging from 10 to 49

arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [ ]:
# 7. Reverse a vector (first element becomes last)

arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [ ]:
# 8. Create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 9. Find indices of non-zero elements from [1,2,0,0,4,0]

arr = np.array([1,2,0,0,4,0])
print(np.nonzero(arr))

(array([0, 1, 4]),)


In [ ]:
# 10. Create a 3x3 identity matrix

arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# 11. Create a 3x3x3 array with random values


arr = np.random.random((3,3,3))
arr

array([[[0.02874852, 0.47801666, 0.91304494],
        [0.434791  , 0.73196746, 0.08058503],
        [0.37648573, 0.71910523, 0.78661705]],

       [[0.15502548, 0.34679292, 0.54091946],
        [0.10602906, 0.68988702, 0.87436116],
        [0.67426744, 0.9860502 , 0.8387419 ]],

       [[0.52634852, 0.11140005, 0.53696539],
        [0.42942491, 0.13896689, 0.02697552],
        [0.63041831, 0.37379647, 0.89017203]]])

In [ ]:
# 12. Create a 10x10 array with random values and find the minimum and maximum values

arr = np.random.random((10,10))
print(arr)
print("Maximum Value = ", arr.max())
print("Minimum Value = ", arr.min())

[[0.92371892 0.19185764 0.77059848 0.41821921 0.96080752 0.50639268
  0.09698947 0.28418532 0.85812549 0.98452465]
 [0.68392196 0.91117124 0.53812201 0.2347573  0.72703059 0.59481203
  0.61240004 0.37272982 0.42442566 0.67178642]
 [0.36831028 0.30298357 0.34378486 0.49888623 0.3213342  0.89005926
  0.12414319 0.06700591 0.22446356 0.02286074]
 [0.42886748 0.22269204 0.91601963 0.1598972  0.94380766 0.3656345
  0.1549122  0.34424772 0.49123416 0.35066008]
 [0.19255999 0.3822487  0.5830042  0.76860494 0.60095374 0.71814475
  0.64413013 0.93135977 0.43298586 0.00680591]
 [0.25517982 0.1526415  0.94037549 0.42882568 0.85711885 0.64901477
  0.31771086 0.3085457  0.2035316  0.17085299]
 [0.42768027 0.44446141 0.19725011 0.33309665 0.58101189 0.77050598
  0.88029252 0.70638493 0.13186652 0.54758462]
 [0.78688847 0.20969343 0.92161071 0.5669922  0.60048071 0.11199048
  0.68155104 0.23178733 0.09725051 0.12075874]
 [0.45349649 0.37043355 0.91235939 0.14884717 0.68834151 0.22574742
  0.11773262 

In [ ]:
# 13. Create a random vector of size 30 and find the mean value

arr = np.random.random((30))
arr.mean()

0.5456567715740618

In [ ]:
# 14. Create a 2d array with 1 on the border and 0 inside

arr = np.ones((4,4))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 15. How to add a border (filled with 0's) around an existing array

arr = np.ones((3,3))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# 16. How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

'''Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20'''

arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print("Get 13 = ",arr[1,5])
print("Get First Row = ",arr[0])
print("Get Third Column = ",arr[:,2])
print("Getting [2, 4, 6] = ",[arr[0,1],arr[0,3],arr[0,5]])
arr[1,5] = 20
print("Replaced 13 by 20 = ", arr)

Get 13 =  13
Get First Row =  [1 2 3 4 5 6 7]
Get Third Column =  [ 3 10]
Getting [2, 4, 6] =  [2, 4, 6]
Replaced 13 by 20 =  [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
# 17. How to Convert a 1D array to a 2D array with 2 rows

arr = np.arange(9)
print(arr)

arr = np.reshape(arr,(3,3))
print(arr)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 18. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

'''Input:
a = np.array([1,2,3])

Desired Output:
 array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])'''

arr = np.array([1,2,3])
np.r_[np.repeat(arr, 3), np.tile(arr, 3)]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
# 19. Write a program to show how Numpy taking less memory compared to Python List?

l = range(1000)
import sys
a = 10
print("List Memory= ",sys.getsizeof(a)*len(l))

n_arr = np.arange(1000)
print("NumPy Memory = ",sys.getsizeof(n_arr))

List Memory=  28000
NumPy Memory =  8096


In [ ]:
# 20. Write a program to show how Numpy taking less time compared to Python List

import time

s = 10000000
l1 = range(s)
l2 = range(s)
start = time.time()
r = [(x+y) for x,y in zip(l1,l2)]
print("Time Taken By List = ",(time.time()-start)*1000)

n1 = np.arange(s)
n2 = np.arange(s)
start = time.time()
r1 = n1+n2
print("Time Taken By NumPy = ",(time.time()-start)*1000)

Time Taken By List =  1375.7529258728027
Time Taken By NumPy =  28.92470359802246
